stages:
  prepare:
    cmd: python3 src/data/split_data.py
    deps:
    - data/raw_data
    - src/data/split_data.py
    outs:
    - data/processed_data
  gridsearch:
    cmd: python3 src/models/gridsearch.py
    deps:
    - data/processed_data/
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed_data/
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.joblib
  predict:
    cmd: python3 src/models/predict_model.py
    deps:
    - data/processed_data/
    - models/trained_model.joblib
    - src/models/predict_model.py
    outs:
    - data/predictions/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
